<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <SonarQubeSetting Include="sonar.coverage.exclusions">
      <Value>**/Migrations/**</Value>
    </SonarQubeSetting>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Flow.Reports.Domain\Flow.Reports.Domain.csproj" />
    <ProjectReference Include="..\Flow.Reports.Application\Flow.Reports.Application.csproj" />
    <ProjectReference Include="..\..\Flow.Shared\Flow.Shared.Infrastructure.Abstractions\Flow.Shared.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
  </ItemGroup>

</Project>
