<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Flow.Aspire\Flow.Aspire.ServiceDefaults\Flow.Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Flow.Transactions.Application\Flow.Transactions.Application.csproj" />
    <ProjectReference Include="..\Flow.Transactions.Infrastructure\Flow.Transactions.Infrastructure.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Aspire.Keycloak.Authentication" Version="13.3.5-preview.1.26270.6" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.3.5" />
    <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.3.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

</Project>
