name: SonarQube

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SOLUTION_DIR: 'src'

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd "${SOLUTION_DIR}"

          dotnet-sonarscanner begin \
            /k:"micheloliveira-com_flow-case" \
            /o:"micheloliveira-com" \
            /d:sonar.token="${SONAR_TOKEN}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.exclusions="**/*.Blazor/**" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml"

          dotnet build

          test_projects=$(find . -type f -iname '*.Tests.csproj')

          if [ -z "$test_projects" ]; then
            echo "No test projects found!"
            exit 1
          fi

          while IFS= read -r test_project; do
            echo "Running tests for: $test_project"

            test_project_dir=$(dirname "$test_project")

            dotnet test "$test_project" \
              --no-build \
              --collect:"XPlat Code Coverage" \
              --results-directory "$test_project_dir/TestResults" \
              -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          done <<< "$test_projects"

          dotnet-sonarscanner end \
            /d:sonar.token="${SONAR_TOKEN}"
