name: SonarQube

permissions:
  contents: read
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
env:
  SOLUTION_DIR: 'src'

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global coverlet.console
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd "${SOLUTION_DIR}"

          dotnet-sonarscanner begin \
            /k:"micheloliveira-com_flow-case" \
            /o:"micheloliveira-com" \
            /d:sonar.token="${SONAR_TOKEN}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.xml"
          
          dotnet build
          
          # Find first folder ending with .Tests (case-insensitive)
          # Find all folders ending with .Tests (case-insensitive)
          test_project_dirs=$(find . -type d -iname '*.tests')

          if [ -z "$test_project_dirs" ]; then
            echo "No test project folders found!"
            exit 1
          fi

          while IFS= read -r test_project_dir; do
            echo "Found test project folder: $test_project_dir"

            project_name=$(basename "$test_project_dir")

            dll_path=$(find "$test_project_dir/bin" -type f -name "${project_name}.dll" | head -n 1)

            if [ -z "$dll_path" ]; then
              echo "No DLL named $project_name.dll found inside $test_project_dir/bin!"
              exit 1
            fi

            echo "Found test DLL: $dll_path"

            coverage_file="$test_project_dir/coverage.xml"

            coverlet "$dll_path" \
                --target "dotnet" \
                --targetargs "test --no-build" \
                -f=opencover \
                -o="$coverage_file"

          done <<< "$test_project_dirs"
              
          dotnet-sonarscanner end /d:sonar.token="${SONAR_TOKEN}"